name: Release Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Authenticate to GitHub Packages using PAT
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Publish to GitHub Packages
        run: npm publish